"""Add todos table

Revision ID: 898fb02cfb9c
Revises: 9c1dfb67ea08
Create Date: 2024-08-19 05:38:00.434377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898fb02cfb9c'
down_revision: Union[str, None] = '9c1dfb67ea08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
